routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/home', function () {
    return view('home');
});

Route::get('/capturaExp', function () {
    return view('expedientes.create');
});

Route::get('/header', function () {
    return view('layouts.header');
});

Route::get('/perfil', function () {
    return view('users.perfil');
});
Route::get('/tutoria', function () {
    return view('users.tutoria');
});

Route::get('/articulo', function () {
    return view('users.articulo');
});
Route::get('/libro', function () {
    return view('users.libro');
});



Route::get('/Gestioncademica', function () {
    return view('users.Gestioncademica');
});
Route::get('/Productos_desarrollados', function () {
    return view('users.Productos_desarrollados');
});
Route::get('/capacitacion', function () {
    return view('users.capacitacion');
});
Route::get('/Eventos', function () {
    return view('users.Eventos');
});


Route::get('/editarperfil', function () {
    return view('users.editarperfil');
});

//PDF capturaExp
Route::get('/capturaExp', 'PdfController@pdfForm');
Route::post('pdf_download', 'PdfController@pdfDownload');

//PDF GestionAcademica
Route::get('/Gestioncademica', 'PdfController@pdfFormGestion');
Route::post('pdf_download_GestionA', 'PdfController@pdfDownload_GestionA');

//PDF Producto_desarrollado
Route::get('/Productos_desarrollados', 'PdfController@pdfFormProductos');
Route::post('pdf_download_productosD', 'PdfController@pdfDownload_Productos');


//Documentos
Route::get('/files/create','DocumentosController@create');
Route::post('/files','DocumentosController@store');

Route::get('/files','DocumentosController@index');
Route::get('/files/{id}','DocumentosController@show');
Route::get('file/download/{file}','DocumentosController@download');

//Busqueda
Route::get('/search','DocumentosController@search');
Route::get('/fechaActual','DocumentosController@fechaActual');
Route::get('/pasado','DocumentosController@primerAño');
Route::get('/antiguo','DocumentosController@tercerAño');

Route::resource('archivos','DocumentosController');


Auth::routes();

app/Documentos.php
<?php

namespace App;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class Documentos extends Eloquent
{
    protected $connection = 'mongodb';
    protected $collection = 'documentos';

    protected $fillable=['titulo','autor','descripcion','file'];
}

app/Http/Controllers/DocumentosController.php
<?php

namespace App\Http\Controllers;

use App\Documentos;
use Illuminate\Http\Request;
class DocumentosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request){
        $search = $request->get('search');
      
        $file=Documentos::where('titulo','like',"%$search%")->get();
        return view('documentos.index',compact('file'));

     }
     public function fechaActual(Request $request){
        $fechaActual = $request->get('fechaActual');      
        $file=Documentos::where('created_at','like',"%$fechaActual%")->get();
        return view('documentos.index',compact('file'));
     }
     public function primerAño(Request $request){
        $pasado = $request->get('pasado');      
        $file=Documentos::where('created_at','like',"%$pasado%")->get();
        return view('documentos.index',compact('file'));
     }
     public function tercerAño(Request $request){
        $antiguo = $request->get('antiguo');      
        $file=Documentos::where('created_at','like',"%$antiguo%")->get();
        return view('documentos.index',compact('file'));
     }
     public function index()
    {
        $file=Documentos::all();
        return view('documentos.index',compact('file'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
     return view('documentos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = new Documentos;
        if($request->file('file')){
            $file=$request->file('file');
            $filename=time().'.'.$file->getClientOriginalExtension();
            $request->file->move('storage/' , $filename);
            
            $data->file=$filename;
        }
        $data->titulo=$request->titulo;
        $data->autor=$request->autor;
        $data->descripcion=$request->descripcion;
        $data->save();
        return redirect()->route('archivos.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data=Documentos::find($id);
        return view('documentos.view',compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function download($file){
        return response()->download('storage/' .$file);
    }

    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Documentos::find($id);
        $data->delete();
        return redirect()->route('archivos.index');
    }
}

resources/views/documentos/create.blade.php
@extends('layouts.app')

@section('Titulo', 'Repositorio de investigaciones ')

@section('content')
<div class="panel-header colorut" >
  <div class="page-inner py-5">
    <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
        <div>
            <h2 class="text-black pb-2 fw-bold">Crear nuevo documento</h2>
          </div>		
        </div>
  </div>
  </div>
<div class="page-inner mt--5">	
<div class="row">
          <div class="col-md-12">
              <div class="card">
                  <div class="card-header">
                      <div class="card-title">Crear un nuevo Documento</div>
                  </div>
              <div class="card-body">
                
      <form action="/files" method="POST" enctype="multipart/form-data">
     <div class="form-row">
        @csrf 
        <div class="form-group col-md-6 ">  
        <label for="inputEmail4">Nombre Del Titulo:</label>
        <input type="text" name="titulo" placeholder="titulo">
      </div>
      <div class="form-group col-md-6 ">
        <label for="inputEmail4">Nombre Del Autor:</label>
        <input type="text" name="autor" placeholder="autor">
      </div>
      <div class="form-group col-md-6 ">
        <label for="inputEmail4">Agregar Descripcion:</label>
          <input type="text" name="descripcion" placeholder="descripcion">
      </div>
          <input type="file"  class="btn btn-light" name="file">
          <input type="submit" class="btn btn-primary" value="Enviar">
      </form>

      @endsection

resources/views/documentos/index.blade.php
@extends('layouts.app')

@section('Titulo', 'Repositorio de investigaciones ')

@section('content')

  <!-- Bootstrap CSS -->
  <div class="panel-header colorut" >
		<div class="page-inner py-5">
			<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
			    <div>
			        <h2 class="text-black pb-2 fw-bold">Documentos realizados</h2>
		        </div>		
	        </div>
		</div>
    </div>
	<div class="page-inner mt--5">	
  <h1>Buscar Por año</h1>				
  <div class="btn-group btn-group-toggle" >
        <?php $fecha = date("Y");?>
        <!--Actualmente--->
          <form action="/fechaActual" method="GET" class="form-inline">
            <button type="submit" name="fechaActual" class="btn btn-default" value="<?php echo $fecha;?>" >Actual</button>
          </form>
          <!--Primer año--->
          <form action="/pasado" method="GET" class="form-inline">
            <button type="submit" name="pasado" class="btn btn-default" value="<?php echo $fecha-1;?>">1 año</button>
          </form>
            <!--Tercer año--->
          <form action="/antiguo" method="GET" class="form-inline">
            <button type="submit" name="antiguo" class="btn btn-default" value="<?php echo $fecha-3;?>">3 años</button>
          </form>
          </div>
    <div class="container">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-6">
                          <table class="table table-striped">

          <tr>
              <th>#</th>
              <th>Titulo</th>
              <th>Autor</th>
              <th>Descripcion</th>
              <th>Ver</th>
              <th>Descargar</th>
              <th>Fecha de Creacion</th>
              <th>Eliminar</th>
            </tr>
                @foreach ($file as $key=>$data)
                <tr>
                    <td>{{++$key}}</td>
                    <td>{{$data->titulo}}</td>
                    <td>{{$data->autor}}</td>
                    <td>{{$data->descripcion}}</td>
                    <td><a class="btn btn-success" href="/files/{{$data->id}}">ver</a></td>
                    <td><a class="btn btn-success" href="/file/download/{{$data->file}}">Descargar</a> </td>
                    <td>{{$data->created_at}}</td>
                    <td>
                        <form action="{{route("archivos.destroy", $data->id)}}" method="POST"> 
                        @method("DELETE")
                        @csrf
                       <input type="submit" class="btn btn-danger" value="Eliminar">
                       </form>
                    </td>
                    </tr>
                @endforeach
      </table>
      @endsection

resources/views/documentos/view.blade.php
@extends('layouts.app')

@section('Titulo', 'Repositorio de investigaciones ')

@section('content')
      <h1 align='center'>PDF</h1>
      <iframe src="{{url('storage/' .$data->file)}}"  width="100%" height="700px">
      </iframe>
  @endsection
  